### ISSUE TITLE
XMLSerializer is not DOM compliant

### ISSUE THREAD

**Issue by thorsteinson** [KeepingFoundThingsFound/itemMirror#49]
## Issue

In order to properly store display text, we rely on the fact that the XML is properly encoded so that any newlines are also saved. This is a key part of markdown, and we expect to be able to store several paragraphs potentially.

However, when we serialize the XML, using the standard [XMLSerializer](https://developer.mozilla.org/en-US/docs/XMLSerializer) it doesn't properly encode these. When the XML is then parsed, the newlines are interpreted as spaces. This [stack-overflow thread](http://stackoverflow.com/questions/2004386/how-to-save-newlines-in-xml-attribute) shows what the non compliant behavior looks like.

## Solution

I fixed this issue by simply using a regular expression to replace newlines in the XML with the encoded symbol before it is written Dropbox. So it __currently behaves as expected__.

## Question

Is it good to rely on something which isn't compliant, and could this lead to possible unintended bugs elsewhere? If we can't use the XMLSerializer, are there better options out there?

**Comment by williampauljones1** [comment]
from our meeting on Monday Feb. 8th.
issue with line breaks. 
there is currently a hack to handle.
look into behavior of XML serializer
tested in Chrome and Firefox so far. 
Browsers may differ in their implementation of serialization. Some variation. 

Next step: Test generic XML file against different browsers, round trip, write/read file should be the same.
