### ISSUE TITLE
Draft outline of steps remaining to have a "turnkey tutorial" for building an iM app

### ISSUE THREAD

**Issue by williampauljones1** [KeepingFoundThingsFound/itemMirror#68]
step by step through wiki pages taking developers through
1. basics in use of iM with minimal additional JS libraries (e.g., with only jQuery and ... ?)
__ show how FolderDocs or similar could be craeted.
__ show how PP or similar (with drag & drop X/Y positioning) can be 
__ other examples (explain Tagether/Knitter and possibly StormNote or NoteU)

2. advanced use with Angular and notion of MVC. 

Note that this is P1 for the next "release" which is March 28th (when Spring Quarter starts).

**Comment by LegalArgumentException** [comment]
Wiki First Draft Outline:

- Introduction to iM

- Initialization (Behind the scenes)

 - Quick overview on getting app keys (app and secret) for Dropbox / Google Drive

 - Point reader to documentation for using oAuth 2.0 (assuming they know how to authorize Dropbox / Google Drive)

- iM Basics

 - Very basic rendering of an iM object

   - Show all associations on page

    - Then, separate in to grouping items / non grouping items

    - Introduction to DisplayText

 - Navigation examples

    - Create iM from associated grouping item

    - Traverse back to parent (prev)

 - Add Simple operations 

    - Delete

    - Rename

    - Show in cloud store

- Namespace attributes

  - Create a new namespace attribute

  - Access an existing namespace attribute

  - Alter an existing namespace attribute

- Adding additional functionality 

  - Example of in-place editing functionality (FolderDocs)

  - Example of drag & drop X/Y positioning (PictureProjector)

  - Other examples (Tagether/Knitter)

- Integration with Angular / MVC framework

  - Can borrow / point to certain areas of Caleb's iM Angular tutorial

**Comment by williampauljones1** [comment]
Caleb, Brandon and I reviewed the outline for the tutorial today and all looks good with the following exceptions:
1.	oAuth 2.0 — good to point people to documentation on this for background reading but I'm not sure we need a separate  bullet for this. i.e., I think developers could do fine without this background.
2.	simple operations: Delete, Rename, Open in cloud store. Add also "Create" of new  subfolder. (late discuss option to create phantom association).  Somewhere later add the option to create a "phantom" association.
3.	namespace attributes —Make clear that this is for persisting metadata which is a _big_ deal.  please plan to discuss the option to persist metadata either at the fragment level (i.e., applying to the whole itemMirror object) or at the level of an association. Give the example of PictureProjector. One namespace attribute (for "startFolder" or whatever you guys called it) is fragment-level  and only used for the root itemMirror object. Other namespace attributes are association-level (e.g., for associatedPicture, and for x/y-position).  Note that associatedPIcture might have been fragment-level but we decided for association level instead. Remember why? ….. two reasons at least: 1. because (once case 4 of createAssocaition is handled) a folder might appear in several different contexts and might want to be represented by a different picture in each. 2. for the sake of efficiency — faster to inspect the attribute of an association than to create an new itemMIrror object for the associated grouping item.
4.	We’re not sure that there is any need to go into the use of Angular (or other  MVC frameworks). There is no special interaction between iM and these frameworks. The interested reader can learn more (but on their own).  Basic libraries iM needs (for tutorial apps like PP and FolderDocs): JS, jQuery and Bootstrap.

**Comment by williampauljones1** [comment]
need to be sure to include a FAQ or "trouble-shooting" page organized by problem/question and solution steps/answer. 
Include in this (and elsewhere) documentation on Save and Refresh.

Problem: _.save_ fails. 
Solution: This has most likely happened because the "write handle" (QUID) of the iM object is no longer valid because another app (or another instance of this app) has completed a save targeting the same item (i.e., the folder represented by your iM object). To complete the _.save_ you will need to get a new  a new write-handle:

1. use the method  _.refresh_ on the iM object. This iM object is now "refreshed" to  agree completely with the item it represents and with attributes that perfectly correspond to the XML metadata for this item. (If the item is a folder, than this metadata is typically stored in a "xooml2.xml" file within the folder.)
2. add any changes you which to persist back into the iM object (e.g., as namespace attributes either at the fragment level or for an association of the iM object).
3. then issue  _.save_ again. 
4. Warning: If another app (or another instance of your app) is actively working with the same item (e.g., a folder) then you may face timing issues and the possibility that even after _.refresh_ of the object, the other app (app instance) has managed to do another _.save_ In this case, you'll need to complete steps 1 thru 3 again.

**Comment by williampauljones1** [comment]
Lots of good work in the wiki!  Good job!
But it might help developers if things are segmented into lessons. See #69

**Comment by williampauljones1** [comment]
I think we're very nearly there with lessons/exercises 1 thru 5 on the wiki.
Let's polish and complete in time for the "Birthday release" (June 1st) as a tutorial to be proud of!
Wm

**Comment by williampauljones1** [comment]
Lessons are completed. We need only to push them into the repository wiki.
